#!/bin/bash
#
# Copyright (C) 2020 by SedexTeam@Github, < https://github.com/SedexTeam >.
#
# This file is part of < https://github.com/SedexTeam/Sedex > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/uaudith/Sedex/blob/master/LICENSE >
#
# All rights reserved.

python3 tools/genStrSession.py
