#!/bin/bash
#
# Copyright (C) 2020-2021 by SedexTeam@Github, < https://github.com/SedexTeam >.
#
# This file is part of < https://github.com/SedexTeam/Sedex > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/SedexTeam/Sedex/blob/master/LICENSE >
#
# All rights reserved.

trap joinProc INT TERM

declare -i bgProc
declare -ir usr1=138
declare -r cmd='. init/init.sh; runSedex "$@"'

setProc() {
    bgProc=$1
}

waitProc() {
    wait $bgProc
}

killProc() {
    kill $bgProc &> /dev/null
}

joinProc() {
    if test $bgProc; then
        killProc
        waitProc
    fi
}

run() {
    joinProc
    bash -c "$cmd" $0 "$@" &
    setProc $!
    waitProc
    test $? -eq $usr1 && run "$@"
}

run "$@"
