version: "3.7"

services:
  sedex:
      build:
        context: https://github.com/code-rgb/sedex-x.git#alpha
      depends_on:
        - mongo
      restart: on-failure
      environment:
          DATABASE_URL: mongodb://root:example@mongo
      env_file:
        - config.env

  mongo:
      image: mongo
      volumes:
        - mongo_sedex:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_sedex:
